services:
  rabbitmq:
    container_name: rabbitmq-dev-1
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - twitch

  redis:
    container_name: redis-dev-1
    image: redis
    networks:
      - twitch
    ports:
      - "6379:6379"

  typesense:
    image: typesense/typesense:0.25.0 # Especifica una versión válida
    container_name: typesense-server-1
    ports:
      - "8108:8108" # Puerto para acceder a Typesense
    volumes:
      - ./data:/data # Persistencia de datos
    networks:
      - twitch
    command: >
      --data-dir /data
      --api-key=0b11111000001
      --enable-cors

networks:
  twitch:
    driver: bridge
